# Generated by Django 5.0.3 on 2024-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('logo_path', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('original_country', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
    ]
