# Generated by Django 5.0.3 on 2024-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productor',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logo_path', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('original_country', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
    ]
