# Generated by Django 5.0.3 on 2024-03-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='idDirector',
            new_name='director',
        ),
    ]
