# Generated by Django 5.0.3 on 2024-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='original_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serie',
            name='poster_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serie',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
