# Generated by Django 5.0.3 on 2024-03-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='season_numbre',
            new_name='number_of_seasons',
        ),
        migrations.AddField(
            model_name='serie',
            name='season_number',
            field=models.IntegerField(default=0),
        ),
    ]
