# Generated by Django 5.0.3 on 2024-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasonDetail',
            fields=[
                ('_id', models.CharField(max_length=30, unique=True)),
                ('air_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster_path', models.CharField(default='', max_length=255)),
                ('season_number', models.IntegerField()),
                ('vote_average', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
