# Generated by Django 5.0.3 on 2024-03-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_seasondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='episodeDetail',
            fields=[
                ('air_date', models.DateField()),
                ('crew', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('runtime', models.IntegerField()),
                ('still_path', models.CharField(default='', max_length=255)),
                ('vote_average', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
