# Generated by Django 5.0.3 on 2024-03-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='also_known_as',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='actor',
            name='biography',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
