# Generated by Django 5.0.3 on 2024-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_also_known_as_actor_biography_actor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
