# Generated by Django 5.0.3 on 2024-03-27 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genders', '0002_rename_idgender_gender_style'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genders.gender')),
                ('idProduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productions.production')),
            ],
        ),
    ]
